import { dayThirteenTask } from './13-day-PointOfIncedence'

// dayOneTask()
// dayTwoTask()
// dayThreeTask()
// dayFourTask()
// dayFiveTask()
// daySixTask()
// daySevenTask()
// dayEightTask()
// dayNineTask()
// dayTenTask()
// dayElevenTask()
// dayTwelveTask()
dayThirteenTask()
